version: '2'
services:
  database:
    expose:
     - "8080"
    volumes:
     - ./database/data:/data
    image: opensesame
  rest_api:
    build:
      context: secunity-backend/
    volumes: 
    - ./secunity-backend/build/libs/secunity-backend-1.0.war:/usr/local/tomcat/webapps/secunity.war
    ports:
    - "8080:8080"
    links:
    - database:db
  frontend:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./frontend:/usr/share/nginx/html:ro
    #- /var/nginx/conf:/etc/nginx:ro -P -d nginx
